### ISSUE TITLE
Question about 2.5D mapping in alexa_reco.launch

### ISSUE THREAD

**Issue by ZackStone233** [laxnpander/OpenREALM#109]
Hello, thank you for maintaining OpenREALM. I noticed that when running alexa_reco.launch, Rviz still displays a 2D map. I found on your forum that you mentioned temporarily suspending the release of 3D grids. Therefore, I would like to ask if you could provide some guidance on publishing and visualizing 3D grids?

**Comment by laxnpander** [comment]
Not really, it's been a long time since I used this feature. I think the export to PLY should still work (hopefully). You can find the relevant flag here, just set it to 1. Then, after being done with mapping just kill the app, which triggers a save to your drive.
https://github.com/laxnpander/OpenREALM_ROS1_Bridge/blob/65a86d465b5ba0b5256f5c8f1bb8090ec3a027f8/realm_ros/profiles/alexa_reco/mosaicing/stage_settings.yaml#L37

If you need meshes while flying this is the relevant code section, but you'd have to debug it yourself. Not sure why it is commented, there seems to be some issue with it:
https://github.com/laxnpander/OpenREALM/blob/91e1e712ffc3d4c8b8b02b3a951d98a8d7817941/modules/realm_stages/src/mosaicing.cpp#L415

**Comment by ZackStone233** [comment]
Thank you very much for your response. I will try to debug that part of the code accordingly.

**Comment by ZackStone233** [comment]
Hello,

I would like to inquire once again regarding the visualization of 2.5D mapping in the `alexa_reco.launch` file within Rviz. Could you please specify which plugin is utilized for this visualization? Additionally, may I know which topic the visualization data is sourced from?

**Comment by laxnpander** [comment]
@ZackStone233: According to this line it is a marker in ROS, if you mean the mesh:

https://github.com/laxnpander/OpenREALM_ROS1_Bridge/blob/65a86d465b5ba0b5256f5c8f1bb8090ec3a027f8/realm_ros/src/realm_ros_lib/stage_node.cpp#L205

**Comment by ZackStone233** [comment]
Thank you very much for your response!
