### ISSUE TITLE
windows platform

### ISSUE THREAD

**Issue by yafenggithub** [laxnpander/OpenREALM#68]
Hello, when does the project plan to support the windows platform? I've been trying recently. I encountered great difficulties and failed. I hope to get help and support the windows platform. Thank you very much.

**Comment by laxnpander** [comment]
@yafenggithub Hey, there is only vague plans to deploy to Windows. It is a lot of work due to the dependencies with e.g. OpenVSLAM and other frameworks that are mainly developed for linux. We need an appropriate visual SLAM that compiles and performs on Windows. Without it, OpenREALM is limited in usefulness. The main library should be easy to migrate, but the dependencies are the tricky part. So: I can't really say and wouldn't want to give too much hope for it to happen in the near future.
